global using IdentityServer4.EntityFramework.DbContexts;
global using IdentityServer4.Services;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Options;
global using System;
global using System.Reflection;
global using IdentityServer4;
global using IdentityServer4.Models;
global using System.Collections.Generic;
global using System.Net;
global using System.Text.RegularExpressions;
global using IdentityModel;
global using System.IdentityModel.Tokens.Jwt;
global using System.Linq;
global using System.Security.Claims;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Authentication;
global using System.ComponentModel.DataAnnotations;
global using Newtonsoft.Json;
global using System.Text;
global using Microsoft.EntityFrameworkCore.Design;
global using System.IO;
global using Microsoft.AspNetCore.Mvc;
global using IdentityServer4.EntityFramework.Entities;
global using IdentityServer4.EntityFramework.Mappers;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using IdentityServer4.Stores;
global using Microsoft.AspNetCore.Authorization;
global using IdentityServer4.Configuration;
global using IdentityServer4.Events;
global using IdentityServer4.Extensions;
global using IdentityServer4.Validation;
global using Microsoft.Extensions.Logging;
global using ApiResource = IdentityServer4.Models.ApiResource;
global using IdentityResource = IdentityServer4.Models.IdentityResource;
global using Client = IdentityServer4.Models.Client;
global using Secret = IdentityServer4.Models.Secret;
global using ApiScope = IdentityServer4.Models.ApiScope;